kind: pipeline
name: publish

steps:
- name: deploy
  image: plugins/docker
  settings:
    repo: mythern/python3-uwsgi-alpine
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    auto_tag: true
